---
- hosts: all
  sudo: yes
  tasks:
  - name: Install docker apt key
    apt_key:
      keyserver: hkp://ha.pool.sks-keyservers.net:80
      id: 58118E89F3A912897C070ADBF76221572C52609D

  - name: Install docker repo
    apt_repository:
      repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"

  - name: Install mongodb apt key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927

  - name: Install mongodb repo
    apt_repository:
      repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"

  - name: Install latest version of "docker" and "mongodb" ignoring "install-recommends"
    apt:
      name: "{{ item.name }}"
      state: latest
      install_recommends: no
    with_items:
      - { name: 'linux-image-extra-4.4.0-57-generic' }
      - { name: 'linux-image-extra-virtual' }
      - { name: 'docker-engine' }
      - { name: 'python-setuptools' }
      - { name: 'python-pkg-resources' }
      - { name: 'python-pip' }
      - { name: 'mongodb-org' }

  - name: Upgrade pip
    pip:
      name: pip
      extra_args: --upgrade

  - name: Install docker-compose
    pip:
      name: docker-compose

  - name: Start mongodb service
    service:
      name: mongod
      state: started