---
  version: '2'

  services:
    mongodb:
      image: mongo

    app:
      build: .
      command: foreman start -d /app
      volumes:
        - ./app:/app
      ports:
        - "80:5678"
      depends_on:
        - mongodb
      links:
        - mongodb
      environment:
        - MONGODB_NAME=development
