source 'http://rubygems.org'

ruby "2.3.1"

gem 'foreman'
gem 'puma'
gem 'sinatra', :require => 'sinatra/base'
gem 'mongoid'
gem 'haml'
gem 'nokogiri'

# for testing

gem 'rake'
gem 'minitest'
gem 'rack'
gem 'rack-test'
gem 'guard'
gem 'guard-minitest'

